spring.application.name=chatapp
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/chatapp
spring.datasource.username=postgres
spring.datasource.password=Deeksha@112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true